### ISSUE TITLE
Intel MEI Driver MSI Installers will not fully extract

### ISSUE THREAD

**Issue by Zexaron** [Bioruebe/UniExtract2#108]
There's a 7zip config file error in the first link, but otherwise seems successful.

It's multiple steps. First it's the single download pack, that extract's fine, second is the SetupME.exe pack, that also seems to extract fine. Then there's individual .MSI files, but some of them don't extract fully or not at all. The ones that do not extract are for the drivers too, it extracts less than 3 megabytes but the .MSI is over 10 Megabytes.

The problematic MSI files can't be extracted with using the "Extract Contents" context command in Windows10, the msiexec process starts and keeps running without doing anything. While UniExtract is able to do it partially, but still missing the actualy DRIVER files.

I just want to get rid of all the intel app blotware and get me those drivers.

First link: https://www.station-drivers.com/index.php?option=com_remository&Itemid=352&func=fileinfo&id=3435&lang=en

Second Link: https://dlcdnets.asus.com/pub/ASUS/misc/utils/MEI_Consumer_V11051189.zip

**Comment by Zexaron** [comment]
Legacy drivers installer has an unextractable cabinet file.

```
C:\Users\User\Downloads\MEI_Consumer_V11051189\Install\SetupME\ME_UnLegacy_x64\media1.cab: no folders in cabinet.

Error: System.Exception: Failed to open cabinet. Last error:MSPACK_ERR_DATAFORMAT
   at LibMSPackN.MSCabinet..ctor(String cabinetFilename)
   at LessMsi.Msi.Wixtracts.MergeCabs(IList`1 cabInfos)
   at LessMsi.Msi.Wixtracts.ExtractFiles(Path msi, String outputDir, MsiFile[] filesToExtract, AsyncCallback progressCallback)
   at LessMsi.Cli.Program.DoExtraction(String msiFileName, String outDirName, List`1 filesToExtract)
   at LessMsi.Cli.ExtractCommand.Run(List`1 allArgs)
   at LessMsi.Cli.Program.Main(String[] args)
```

**Comment by Zexaron** [comment]
Just trying to Install it, does "nothing", but it dumps the actual drivers into Temp, actually only for the UnLegacy, but installing the ordinary driver MSI did actually install and did not dump.

Sort of got what I wanted anyway but hope it actually works and it installed properly. I do have all the filesystem events saved in a process monitor logfile if it helps.

From Uniextact point of view, this still doesn't work and I consider it not fully solved, but I kinda got what I needed.

**Comment by HapaxOromenon** [comment]
Note that Intel do provide packages containing just the drivers - at https://downloadcenter.intel.com/download/27733/Intel-Management-Engine-Driver-for-Windows-7-8-1-and-Windows-10, they provide a ZIP file. Opening this file reveals that in the folder "Consumer", there are three folders - "ME_SW_MSI" contains a setup that installs the full drivers and software; "MEI-Only Installer MSI" contains a setup that installs only the drivers and not the software; there's also "WindowsDriverPackages", containing INF files that you can use to ensure that drivers directly through Device Manager (right-click -> Update Driver -> Browse my computer for driver software -> Let me pick from a list of available drivers on my computer -> Have Disk, and then select the INF file), which will definitely ensure that no unwanted software gets installed.

**Comment by Zexaron** [comment]
Actually, I never knew this before, until now when I went digging into it this deeply.

There is no drivers inside the INF setup utility, it's a fake driver package, used to remove the warnings windows shows, I'm not sure if this is for a lot of chipsets/motherboards, but that's it, it all points back to a common machine.inf and drivers that Windows already has included, very funny, veeeeery funny.

> `; ************************************************************
; ************************************************************
; **  Filename: PatsburgSystem.inf                          **
; **  Abstract: Assigns the null driver to devices          **
; **            for yellow-bang removal and                 **
; **            brands Intel(R) devices                     ** 
; ************************************************************
; ************************************************************

[Version]
Signature=$WINDOWS NT$
Class=System
ClassGUID={4D36E97D-E325-11CE-BFC1-08002BE10318}
Provider=%INTEL%
CatalogFile=Patsburg.cat
DriverVer=01/01/1970, 10.1.1.42

[SourceDisksNames]

[SourceDisksFiles]

[ControlFlags]
ExcludeFromSelect=*

[PackageInfo]
Name=Chipset

[Manufacturer]
%INTEL%=INTEL,NT,NTamd64

[INTEL.NT]
%PCI\VEN_8086&DEV_1D10Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D10
%PCI\VEN_8086&DEV_1D11Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D11
%PCI\VEN_8086&DEV_1D12Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D12
%PCI\VEN_8086&DEV_1D13Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D13
%PCI\VEN_8086&DEV_1D14Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D14
%PCI\VEN_8086&DEV_1D15Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D15
%PCI\VEN_8086&DEV_1D16Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D16
%PCI\VEN_8086&DEV_1D17Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D17
%PCI\VEN_8086&DEV_1D18Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D18
%PCI\VEN_8086&DEV_1D19Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D19
%PCI\VEN_8086&DEV_1D1ADesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1A
%PCI\VEN_8086&DEV_1D1BDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1B
%PCI\VEN_8086&DEV_1D1CDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1C
%PCI\VEN_8086&DEV_1D1DDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1D
%PCI\VEN_8086&DEV_1D1EDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1E
%PCI\VEN_8086&DEV_1D1FDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1F
%PCI\VEN_8086&DEV_1D22Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D22
%PCI\VEN_8086&DEV_1D24Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D24
%PCI\VEN_8086&DEV_1D25Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D25
%PCI\VEN_8086&DEV_1D3EDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D3E
%PCI\VEN_8086&DEV_1D3FDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D3F
%PCI\VEN_8086&DEV_1D40Desc%=Needs_ISAPNP_DRV,PCI\VEN_8086&DEV_1D40
%PCI\VEN_8086&DEV_1D41Desc%=Needs_ISAPNP_DRV,PCI\VEN_8086&DEV_1D41
%PCI\VEN_8086&DEV_1D70Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D70
%PCI\VEN_8086&DEV_1D71Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D71
%PCI\VEN_8086&DEV_1D72Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D72
%PCI\VEN_8086&DEV_1D73Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D73
%PCI\VEN_8086&DEV_1D74Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D74
%PCI\VEN_8086&DEV_1D76Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D76
%PCI\VEN_8086&DEV_1D77Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D77

[INTEL.NTamd64]
%PCI\VEN_8086&DEV_1D10Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D10
%PCI\VEN_8086&DEV_1D11Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D11
%PCI\VEN_8086&DEV_1D12Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D12
%PCI\VEN_8086&DEV_1D13Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D13
%PCI\VEN_8086&DEV_1D14Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D14
%PCI\VEN_8086&DEV_1D15Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D15
%PCI\VEN_8086&DEV_1D16Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D16
%PCI\VEN_8086&DEV_1D17Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D17
%PCI\VEN_8086&DEV_1D18Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D18
%PCI\VEN_8086&DEV_1D19Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D19
%PCI\VEN_8086&DEV_1D1ADesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1A
%PCI\VEN_8086&DEV_1D1BDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1B
%PCI\VEN_8086&DEV_1D1CDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1C
%PCI\VEN_8086&DEV_1D1DDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1D
%PCI\VEN_8086&DEV_1D1EDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1E
%PCI\VEN_8086&DEV_1D1FDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D1F
%PCI\VEN_8086&DEV_1D22Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D22
%PCI\VEN_8086&DEV_1D24Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D24
%PCI\VEN_8086&DEV_1D25Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D25
%PCI\VEN_8086&DEV_1D3EDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D3E
%PCI\VEN_8086&DEV_1D3FDesc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D3F
%PCI\VEN_8086&DEV_1D40Desc%=Needs_ISAPNP_DRV,PCI\VEN_8086&DEV_1D40
%PCI\VEN_8086&DEV_1D41Desc%=Needs_ISAPNP_DRV,PCI\VEN_8086&DEV_1D41
%PCI\VEN_8086&DEV_1D70Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D70
%PCI\VEN_8086&DEV_1D71Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D71
%PCI\VEN_8086&DEV_1D72Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D72
%PCI\VEN_8086&DEV_1D73Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D73
%PCI\VEN_8086&DEV_1D74Desc%=Needs_PCI_DRV,PCI\VEN_8086&DEV_1D74
%PCI\VEN_8086&DEV_1D76Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D76
%PCI\VEN_8086&DEV_1D77Desc%=Needs_NO_DRV,PCI\VEN_8086&DEV_1D77

[Needs_PCI_DRV]
Include=machine.inf
Needs=PCI_DRV

[Needs_PCI_DRV.Services]
Include=machine.inf
Needs=PCI_DRV.Services

[Needs_PCI_DRV.HW]
Include=machine.inf
Needs=PCI_DRV.HW

[Needs_NO_DRV]
Include=machine.inf
Needs=NO_DRV

[Needs_NO_DRV.Services]
Include=machine.inf
Needs=NO_DRV.Services

[Needs_ISAPNP_DRV]
Include=machine.inf
Needs=ISAPNP_DRV

[Needs_ISAPNP_DRV.Services]
Include=machine.inf
Needs=ISAPNP_DRV.Services

[Strings]
INTEL="INTEL"
PCI\VEN_8086&DEV_1D10Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 1 - 1D10"
PCI\VEN_8086&DEV_1D11Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 1 - 1D11"
PCI\VEN_8086&DEV_1D12Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 2 - 1D12"
PCI\VEN_8086&DEV_1D13Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 2 - 1D13"
PCI\VEN_8086&DEV_1D14Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 3 - 1D14"
PCI\VEN_8086&DEV_1D15Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 3 - 1D15"
PCI\VEN_8086&DEV_1D16Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 4 - 1D16"
PCI\VEN_8086&DEV_1D17Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 4 - 1D17"
PCI\VEN_8086&DEV_1D18Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 5 - 1D18"
PCI\VEN_8086&DEV_1D19Desc="Intel(R) C600/X79 series chipset PCI Express Root Port 5 - 1D19"
PCI\VEN_8086&DEV_1D1ADesc="Intel(R) C600/X79 series chipset PCI Express Root Port 6 - 1D1A"
PCI\VEN_8086&DEV_1D1BDesc="Intel(R) C600/X79 series chipset PCI Express Root Port 6 - 1D1B"
PCI\VEN_8086&DEV_1D1CDesc="Intel(R) C600/X79 series chipset PCI Express Root Port 7 - 1D1C"
PCI\VEN_8086&DEV_1D1DDesc="Intel(R) C600/X79 series chipset PCI Express Root Port 7 - 1D1D"
PCI\VEN_8086&DEV_1D1EDesc="Intel(R) C600/X79 series chipset PCI Express Root Port 8 - 1D1E"
PCI\VEN_8086&DEV_1D1FDesc="Intel(R) C600/X79 series chipset PCI Express Root Port 8 - 1D1F"
PCI\VEN_8086&DEV_1D22Desc="Intel(R) C600/X79 series chipset SMBus Host Controller - 1D22"
PCI\VEN_8086&DEV_1D24Desc="Intel(R) C600/X79 series chipset Thermal Management Controller - 1D24"
PCI\VEN_8086&DEV_1D25Desc="Intel(R) C600/X79 series chipset DMI to PCI Bridge - 1D25"
PCI\VEN_8086&DEV_1D3EDesc="Intel(R) C600/X79 series chipset PCI Express Virtual Switch Port - 1D3E"
PCI\VEN_8086&DEV_1D3FDesc="Intel(R) C600/X79 series chipset Virtual Switch Port - 1D3F"
PCI\VEN_8086&DEV_1D40Desc="Intel(R) C600/X79 series chipset LPC Controller - 1D40"
PCI\VEN_8086&DEV_1D41Desc="Intel(R) C600/X79 series chipset LPC Controller - 1D41"
PCI\VEN_8086&DEV_1D70Desc="Intel(R) C600/X79 series chipset SMBus Controller 0 - 1D70"
PCI\VEN_8086&DEV_1D71Desc="Intel(R) C600/X79 series chipset SMBus Controller 1 - 1D71"
PCI\VEN_8086&DEV_1D72Desc="Intel(R) C600/X79 series chipset SMBus Controller 2 - 1D72"
PCI\VEN_8086&DEV_1D73Desc="Intel(R) C600/X79 series chipset Integrated NVSRAM Controller - 1D73"
PCI\VEN_8086&DEV_1D74Desc="Intel(R) C600/X79 series chipset PCI Express Upstream Port - 1D74"
PCI\VEN_8086&DEV_1D76Desc="Intel(R) C600/X79 series chipset Multi - Function Glue - 1D76"
PCI\VEN_8086&DEV_1D77Desc="Intel(R) C600/X79 series chipset PCI Data Acquisition and Signal Processing Controller - 1D77"




; Copyright (c) 2003-2017 Intel Corporation
; 
; ********************************************************************************
; Intel is making no claims of usability, efficacy or warranty.
; ********************************************************************************
; Information in this document is provided in connection with Intel products. No
; license, express or implied, by estoppel or otherwise, to any intellectual
; property rights is granted by this document. Intel assumes no liability
; whatsoever, and Intel disclaims any express or implied warranty, relating to
; sale and/or use of Intel products including liability or warranties relating to
; fitness for a particular purpose, merchantability, or infringement of any
; patent, copyright or other intellectual property right. Intel products are not
; intended for use in medical, life saving, or life sustaining applications.
; ********************************************************************************
; Intel Corporation disclaims all warranties and liabilities for the use of this
; document and the information contained herein, and assumes no responsibility for
; any errors which may appear in this document, nor does Intel make a commitment
; to update the information contained herein. Intel reserves the right to make
; changes to this document at any time, without notice.
; ********************************************************************************
; ********************************************************************************
; 
; * Third-party brands and names are the property of their respective owners.
`

What a load of junk. All of those 1-2-3 adices "don't forget to install chipset drivers" it's all nonsense.

**Comment by HapaxOromenon** [comment]
I'm not sure where this PatsburgSystem.inf file you copied and pasted is from - if you download from the link I provided, you'll find that the file is called heci.inf and does point to an actual .sys file called TeeDriverW8.sys or TeeDriverW8x64.sys, depending on whether you have a 32-bit or 64-bit system. Anyway, .sys files are the actual executable code that talks to the hardware, so this is a real driver. But where you're correct is in saying that chipset drivers do not need to be installed - that is true for the most part. The only times when you should install them are:
(1) if you want to squeeze every bit of performance out of the hard drive, installing the chipset driver may give you faster speeds through the SATA controller, or it might do nothing. In any case, modern SSDs and 7200 RPM hard drivers kind of make this irrelevant; and
(2) if you need certain features of your motherboard that aren't working with the default Windows drivers, then usually the fix is to install the chipset drivers. But do note that Windows 10 out of the box is pretty good on this front, especially compared to e.g. Windows 7, which couldn't even use USB 3 ports with the Microsoft driver.

**Comment by Zexaron** [comment]
You're right, sorry, I forgot to explain, the MEI stuff is all right, there is a driver, but it took using the "extract contents" for it to work or peeking into Temp, just using uniextractor didn't seem to work, or I've heavily missed something.

There's 2 drivers, MEI and RST for Sata, that's all there is, there's no Chipset drivers of any kind, this got me confused. PatsburgSystem.inf is inside the driver repository - System32/driverstore/filerepository - that's all that gets placed by the INF Chipset utility. I know this is a side topic, I never knew that before and I've discovered it that's why it's kinda taking the attention.

I thought the Sata drivers would be in the MEI package, they're not suppose to be there, that's fine now, however, the size discrepancy is still mysterious, that's the main thing why I think not everything got extracted.
